Update azure-static-web-apps-witty-desert-05c3d5703.yml

diff --git a/.github/workflows/azure-static-web-apps-witty-desert-05c3d5703.yml b/.github/workflows/azure-static-web-apps-witty-desert-05c3d5703.yml
--- a/.github/workflows/azure-static-web-apps-witty-desert-05c3d5703.yml
+++ b/.github/workflows/azure-static-web-apps-witty-desert-05c3d5703.yml
@@ -29,22 +29,32 @@ jobs:
         id: idtoken
         with:
            script: |
-               const coredemo = require('@actions/core')
-               return await coredemo.getIDToken()
+            const token = await github.rest.actions.createWorkflowDispatch({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              workflow_id: 'dummy.yml', # This doesn't matter, we're just getting a token
+              ref: context.ref
+            });
+            return token;
            result-encoding: string
+      - name: Check if Secret is Set
+        run: |
+          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_DESERT_05C3D5703 }}" ]; then
+            echo "ERROR: Token is not set."
+            exit 1
+          else
+            echo "Token is set successfully."
+          fi
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
         with:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_DESERT_05C3D5703 }}
           action: "upload"
-          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
-          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
           app_location: "./waste-watch" # App source code path
           output_location: "dist/waste-watch"
           app_artifact_location: "dist/waste-watch" # Built app content directory - optional
           github_id_token: ${{ steps.idtoken.outputs.result }}
-          ###### End of Repository/Build Configurations ######
 
   close_pull_request_job:
     if: github.event_name == 'pull_request' && github.event.action == 'closed'
